# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8dcdbdfaea46302be158cec8e9ec4163ee70a9d978da6113ae7ecf70b915a2d4625e62f4c5d08e392a6c421b57907c82eec694e247e6db8f73db84c80766667

test:
  secret_key_base: a69d4e0cde1f43ffea73dae942047b98648d86391d98d9697bef85e40f7cb703d16c2b49fab278e5f061faa7883b2a96219f86f6ce42f64e0b2f4a87ce1d0562

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
